name: test-lint
on:
  pull_request:
    branches:
      - main
jobs:
  test-lint:
    name: Testing & Checking linter
    environment: Testing
    runs-on: ubuntu-latest
    steps:
      # Access repo
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Add .env from Secrets
        run: |
          touch .env
          echo "NU_AUTH_PWD=${{ secrets.NU_AUTH_PWD }}" >> .env
          echo "NU_AUTH_USERNAME=${{ secrets.NU_AUTH_USERNAME }}" >> .env
      
      - name: Install modules
        run: yarn

      - name: Run Linter
        run: yarn lint

      - name: Run tests
        run: yarn test
