name: test-lint
on: [push]
jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      # Access repo
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install modules
        run: yarn
      - name: Run test
        run: yarn test
